services:
  bff:
    environment:
      BARCODEGEN_URL: ""
      BILLING_URL: ""
      AI_URL: ""
      HISTORY_URL: ""
      AUTH_URL: ""
      NOTIFICATIONS_URL: ""
      TRANS_HISTORY_URL: ""

  worker:
    environment:
      BARCODEGEN_URL: ""
      BILLING_URL: ""
      AI_URL: ""

