// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Login_FullMethodName                       = "/auth.AuthService/login"
	AuthService_Register_FullMethodName                    = "/auth.AuthService/register"
	AuthService_RefreshToken_FullMethodName                = "/auth.AuthService/refreshToken"
	AuthService_TelegramAuth_FullMethodName                = "/auth.AuthService/telegramAuth"
	AuthService_TelegramLogin_FullMethodName               = "/auth.AuthService/telegramLogin"
	AuthService_LinkTelegramAccount_FullMethodName         = "/auth.AuthService/linkTelegramAccount"
	AuthService_EnableSeedPhrase_FullMethodName            = "/auth.AuthService/enableSeedPhrase"
	AuthService_VerifySeedPhrase_FullMethodName            = "/auth.AuthService/verifySeedPhrase"
	AuthService_DisableSeedPhrase_FullMethodName           = "/auth.AuthService/disableSeedPhrase"
	AuthService_GetSeedPhraseStatus_FullMethodName         = "/auth.AuthService/getSeedPhraseStatus"
	AuthService_ChangePassword_FullMethodName              = "/auth.AuthService/changePassword"
	AuthService_ChangeEmail_FullMethodName                 = "/auth.AuthService/changeEmail"
	AuthService_ChangeTelegramAccount_FullMethodName       = "/auth.AuthService/changeTelegramAccount"
	AuthService_TerminateAllSessions_FullMethodName        = "/auth.AuthService/terminateAllSessions"
	AuthService_LinkEmailToAccount_FullMethodName          = "/auth.AuthService/linkEmailToAccount"
	AuthService_SyncUsername_FullMethodName                = "/auth.AuthService/syncUsername"
	AuthService_ChangeUsername_FullMethodName              = "/auth.AuthService/changeUsername"
	AuthService_ChangeNickname_FullMethodName              = "/auth.AuthService/changeNickname"
	AuthService_ChangeTelegramUsername_FullMethodName      = "/auth.AuthService/changeTelegramUsername"
	AuthService_ChangeAvatar_FullMethodName                = "/auth.AuthService/changeAvatar"
	AuthService_GetUserIdentity_FullMethodName             = "/auth.AuthService/getUserIdentity"
	AuthService_GetUserProfile_FullMethodName              = "/auth.AuthService/getUserProfile"
	AuthService_SuggestUsernameAlternatives_FullMethodName = "/auth.AuthService/suggestUsernameAlternatives"
	AuthService_Enable2FA_FullMethodName                   = "/auth.AuthService/enable2FA"
	AuthService_Verify2FA_FullMethodName                   = "/auth.AuthService/verify2FA"
	AuthService_Disable2FA_FullMethodName                  = "/auth.AuthService/disable2FA"
	AuthService_GetAnomalyStats_FullMethodName             = "/auth.AuthService/getAnomalyStats"
	AuthService_GetAccountReadiness_FullMethodName         = "/auth.AuthService/getAccountReadiness"
	AuthService_GetTelegramIdentityHistory_FullMethodName  = "/auth.AuthService/getTelegramIdentityHistory"
	AuthService_GetPublicProfile_FullMethodName            = "/auth.AuthService/getPublicProfile"
	AuthService_FindUserByUsername_FullMethodName          = "/auth.AuthService/findUserByUsername"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	TelegramAuth(ctx context.Context, in *TelegramAuthRequest, opts ...grpc.CallOption) (*TelegramAuthResponse, error)
	TelegramLogin(ctx context.Context, in *TelegramLoginRequest, opts ...grpc.CallOption) (*TelegramLoginResponse, error)
	LinkTelegramAccount(ctx context.Context, in *LinkTelegramRequest, opts ...grpc.CallOption) (*LinkTelegramResponse, error)
	// Seed phrase methods for access
	EnableSeedPhrase(ctx context.Context, in *EnableSeedPhraseRequest, opts ...grpc.CallOption) (*EnableSeedPhraseResponse, error)
	VerifySeedPhrase(ctx context.Context, in *VerifySeedPhraseRequest, opts ...grpc.CallOption) (*VerifySeedPhraseResponse, error)
	DisableSeedPhrase(ctx context.Context, in *DisableSeedPhraseRequest, opts ...grpc.CallOption) (*DisableSeedPhraseResponse, error)
	GetSeedPhraseStatus(ctx context.Context, in *GetSeedPhraseStatusRequest, opts ...grpc.CallOption) (*GetSeedPhraseStatusResponse, error)
	// User profile management
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailResponse, error)
	ChangeTelegramAccount(ctx context.Context, in *ChangeTelegramAccountRequest, opts ...grpc.CallOption) (*ChangeTelegramAccountResponse, error)
	TerminateAllSessions(ctx context.Context, in *TerminateAllSessionsRequest, opts ...grpc.CallOption) (*TerminateAllSessionsResponse, error)
	LinkEmailToAccount(ctx context.Context, in *LinkEmailRequest, opts ...grpc.CallOption) (*LinkEmailResponse, error)
	SyncUsername(ctx context.Context, in *SyncUsernameRequest, opts ...grpc.CallOption) (*SyncUsernameResponse, error)
	// User identity management
	ChangeUsername(ctx context.Context, in *ChangeUsernameRequest, opts ...grpc.CallOption) (*ChangeUsernameResponse, error)
	ChangeNickname(ctx context.Context, in *ChangeNicknameRequest, opts ...grpc.CallOption) (*ChangeNicknameResponse, error)
	ChangeTelegramUsername(ctx context.Context, in *ChangeTelegramUsernameRequest, opts ...grpc.CallOption) (*ChangeTelegramUsernameResponse, error)
	ChangeAvatar(ctx context.Context, in *ChangeAvatarRequest, opts ...grpc.CallOption) (*ChangeAvatarResponse, error)
	GetUserIdentity(ctx context.Context, in *GetUserIdentityRequest, opts ...grpc.CallOption) (*GetUserIdentityResponse, error)
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	SuggestUsernameAlternatives(ctx context.Context, in *SuggestUsernameAlternativesRequest, opts ...grpc.CallOption) (*SuggestUsernameAlternativesResponse, error)
	// Two-Factor Authentication
	Enable2FA(ctx context.Context, in *Enable2FARequest, opts ...grpc.CallOption) (*Enable2FAResponse, error)
	Verify2FA(ctx context.Context, in *Verify2FARequest, opts ...grpc.CallOption) (*Verify2FAResponse, error)
	Disable2FA(ctx context.Context, in *Disable2FARequest, opts ...grpc.CallOption) (*Disable2FAResponse, error)
	// Anomaly detection
	GetAnomalyStats(ctx context.Context, in *GetAnomalyStatsRequest, opts ...grpc.CallOption) (*GetAnomalyStatsResponse, error)
	// Account readiness для frontend
	GetAccountReadiness(ctx context.Context, in *GetAccountReadinessRequest, opts ...grpc.CallOption) (*GetAccountReadinessResponse, error)
	// Административный аудит: история смен Telegram (только admin)
	GetTelegramIdentityHistory(ctx context.Context, in *GetTelegramIdentityHistoryRequest, opts ...grpc.CallOption) (*GetTelegramIdentityHistoryResponse, error)
	// Межсервисные операции (только доверенные сервисы по service key)
	GetPublicProfile(ctx context.Context, in *GetPublicProfileRequest, opts ...grpc.CallOption) (*PublicProfileResponse, error)
	FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) TelegramAuth(ctx context.Context, in *TelegramAuthRequest, opts ...grpc.CallOption) (*TelegramAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramAuthResponse)
	err := c.cc.Invoke(ctx, AuthService_TelegramAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) TelegramLogin(ctx context.Context, in *TelegramLoginRequest, opts ...grpc.CallOption) (*TelegramLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_TelegramLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LinkTelegramAccount(ctx context.Context, in *LinkTelegramRequest, opts ...grpc.CallOption) (*LinkTelegramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkTelegramResponse)
	err := c.cc.Invoke(ctx, AuthService_LinkTelegramAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EnableSeedPhrase(ctx context.Context, in *EnableSeedPhraseRequest, opts ...grpc.CallOption) (*EnableSeedPhraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableSeedPhraseResponse)
	err := c.cc.Invoke(ctx, AuthService_EnableSeedPhrase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifySeedPhrase(ctx context.Context, in *VerifySeedPhraseRequest, opts ...grpc.CallOption) (*VerifySeedPhraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySeedPhraseResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifySeedPhrase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DisableSeedPhrase(ctx context.Context, in *DisableSeedPhraseRequest, opts ...grpc.CallOption) (*DisableSeedPhraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableSeedPhraseResponse)
	err := c.cc.Invoke(ctx, AuthService_DisableSeedPhrase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetSeedPhraseStatus(ctx context.Context, in *GetSeedPhraseStatusRequest, opts ...grpc.CallOption) (*GetSeedPhraseStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeedPhraseStatusResponse)
	err := c.cc.Invoke(ctx, AuthService_GetSeedPhraseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeEmailResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeTelegramAccount(ctx context.Context, in *ChangeTelegramAccountRequest, opts ...grpc.CallOption) (*ChangeTelegramAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeTelegramAccountResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeTelegramAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) TerminateAllSessions(ctx context.Context, in *TerminateAllSessionsRequest, opts ...grpc.CallOption) (*TerminateAllSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateAllSessionsResponse)
	err := c.cc.Invoke(ctx, AuthService_TerminateAllSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LinkEmailToAccount(ctx context.Context, in *LinkEmailRequest, opts ...grpc.CallOption) (*LinkEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkEmailResponse)
	err := c.cc.Invoke(ctx, AuthService_LinkEmailToAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SyncUsername(ctx context.Context, in *SyncUsernameRequest, opts ...grpc.CallOption) (*SyncUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_SyncUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeUsername(ctx context.Context, in *ChangeUsernameRequest, opts ...grpc.CallOption) (*ChangeUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeNickname(ctx context.Context, in *ChangeNicknameRequest, opts ...grpc.CallOption) (*ChangeNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeNicknameResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeTelegramUsername(ctx context.Context, in *ChangeTelegramUsernameRequest, opts ...grpc.CallOption) (*ChangeTelegramUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeTelegramUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeTelegramUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeAvatar(ctx context.Context, in *ChangeAvatarRequest, opts ...grpc.CallOption) (*ChangeAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeAvatarResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserIdentity(ctx context.Context, in *GetUserIdentityRequest, opts ...grpc.CallOption) (*GetUserIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserIdentityResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SuggestUsernameAlternatives(ctx context.Context, in *SuggestUsernameAlternativesRequest, opts ...grpc.CallOption) (*SuggestUsernameAlternativesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestUsernameAlternativesResponse)
	err := c.cc.Invoke(ctx, AuthService_SuggestUsernameAlternatives_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Enable2FA(ctx context.Context, in *Enable2FARequest, opts ...grpc.CallOption) (*Enable2FAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Enable2FAResponse)
	err := c.cc.Invoke(ctx, AuthService_Enable2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Verify2FA(ctx context.Context, in *Verify2FARequest, opts ...grpc.CallOption) (*Verify2FAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Verify2FAResponse)
	err := c.cc.Invoke(ctx, AuthService_Verify2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Disable2FA(ctx context.Context, in *Disable2FARequest, opts ...grpc.CallOption) (*Disable2FAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Disable2FAResponse)
	err := c.cc.Invoke(ctx, AuthService_Disable2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAnomalyStats(ctx context.Context, in *GetAnomalyStatsRequest, opts ...grpc.CallOption) (*GetAnomalyStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnomalyStatsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetAnomalyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAccountReadiness(ctx context.Context, in *GetAccountReadinessRequest, opts ...grpc.CallOption) (*GetAccountReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountReadinessResponse)
	err := c.cc.Invoke(ctx, AuthService_GetAccountReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetTelegramIdentityHistory(ctx context.Context, in *GetTelegramIdentityHistoryRequest, opts ...grpc.CallOption) (*GetTelegramIdentityHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelegramIdentityHistoryResponse)
	err := c.cc.Invoke(ctx, AuthService_GetTelegramIdentityHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetPublicProfile(ctx context.Context, in *GetPublicProfileRequest, opts ...grpc.CallOption) (*PublicProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_GetPublicProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindUserByUsername(ctx context.Context, in *FindUserByUsernameRequest, opts ...grpc.CallOption) (*FindUserByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserByUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_FindUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	TelegramAuth(context.Context, *TelegramAuthRequest) (*TelegramAuthResponse, error)
	TelegramLogin(context.Context, *TelegramLoginRequest) (*TelegramLoginResponse, error)
	LinkTelegramAccount(context.Context, *LinkTelegramRequest) (*LinkTelegramResponse, error)
	// Seed phrase methods for access
	EnableSeedPhrase(context.Context, *EnableSeedPhraseRequest) (*EnableSeedPhraseResponse, error)
	VerifySeedPhrase(context.Context, *VerifySeedPhraseRequest) (*VerifySeedPhraseResponse, error)
	DisableSeedPhrase(context.Context, *DisableSeedPhraseRequest) (*DisableSeedPhraseResponse, error)
	GetSeedPhraseStatus(context.Context, *GetSeedPhraseStatusRequest) (*GetSeedPhraseStatusResponse, error)
	// User profile management
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	ChangeEmail(context.Context, *ChangeEmailRequest) (*ChangeEmailResponse, error)
	ChangeTelegramAccount(context.Context, *ChangeTelegramAccountRequest) (*ChangeTelegramAccountResponse, error)
	TerminateAllSessions(context.Context, *TerminateAllSessionsRequest) (*TerminateAllSessionsResponse, error)
	LinkEmailToAccount(context.Context, *LinkEmailRequest) (*LinkEmailResponse, error)
	SyncUsername(context.Context, *SyncUsernameRequest) (*SyncUsernameResponse, error)
	// User identity management
	ChangeUsername(context.Context, *ChangeUsernameRequest) (*ChangeUsernameResponse, error)
	ChangeNickname(context.Context, *ChangeNicknameRequest) (*ChangeNicknameResponse, error)
	ChangeTelegramUsername(context.Context, *ChangeTelegramUsernameRequest) (*ChangeTelegramUsernameResponse, error)
	ChangeAvatar(context.Context, *ChangeAvatarRequest) (*ChangeAvatarResponse, error)
	GetUserIdentity(context.Context, *GetUserIdentityRequest) (*GetUserIdentityResponse, error)
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	SuggestUsernameAlternatives(context.Context, *SuggestUsernameAlternativesRequest) (*SuggestUsernameAlternativesResponse, error)
	// Two-Factor Authentication
	Enable2FA(context.Context, *Enable2FARequest) (*Enable2FAResponse, error)
	Verify2FA(context.Context, *Verify2FARequest) (*Verify2FAResponse, error)
	Disable2FA(context.Context, *Disable2FARequest) (*Disable2FAResponse, error)
	// Anomaly detection
	GetAnomalyStats(context.Context, *GetAnomalyStatsRequest) (*GetAnomalyStatsResponse, error)
	// Account readiness для frontend
	GetAccountReadiness(context.Context, *GetAccountReadinessRequest) (*GetAccountReadinessResponse, error)
	// Административный аудит: история смен Telegram (только admin)
	GetTelegramIdentityHistory(context.Context, *GetTelegramIdentityHistoryRequest) (*GetTelegramIdentityHistoryResponse, error)
	// Межсервисные операции (только доверенные сервисы по service key)
	GetPublicProfile(context.Context, *GetPublicProfileRequest) (*PublicProfileResponse, error)
	FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) TelegramAuth(context.Context, *TelegramAuthRequest) (*TelegramAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TelegramAuth not implemented")
}
func (UnimplementedAuthServiceServer) TelegramLogin(context.Context, *TelegramLoginRequest) (*TelegramLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TelegramLogin not implemented")
}
func (UnimplementedAuthServiceServer) LinkTelegramAccount(context.Context, *LinkTelegramRequest) (*LinkTelegramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkTelegramAccount not implemented")
}
func (UnimplementedAuthServiceServer) EnableSeedPhrase(context.Context, *EnableSeedPhraseRequest) (*EnableSeedPhraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableSeedPhrase not implemented")
}
func (UnimplementedAuthServiceServer) VerifySeedPhrase(context.Context, *VerifySeedPhraseRequest) (*VerifySeedPhraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySeedPhrase not implemented")
}
func (UnimplementedAuthServiceServer) DisableSeedPhrase(context.Context, *DisableSeedPhraseRequest) (*DisableSeedPhraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableSeedPhrase not implemented")
}
func (UnimplementedAuthServiceServer) GetSeedPhraseStatus(context.Context, *GetSeedPhraseStatusRequest) (*GetSeedPhraseStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeedPhraseStatus not implemented")
}
func (UnimplementedAuthServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAuthServiceServer) ChangeEmail(context.Context, *ChangeEmailRequest) (*ChangeEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (UnimplementedAuthServiceServer) ChangeTelegramAccount(context.Context, *ChangeTelegramAccountRequest) (*ChangeTelegramAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeTelegramAccount not implemented")
}
func (UnimplementedAuthServiceServer) TerminateAllSessions(context.Context, *TerminateAllSessionsRequest) (*TerminateAllSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateAllSessions not implemented")
}
func (UnimplementedAuthServiceServer) LinkEmailToAccount(context.Context, *LinkEmailRequest) (*LinkEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkEmailToAccount not implemented")
}
func (UnimplementedAuthServiceServer) SyncUsername(context.Context, *SyncUsernameRequest) (*SyncUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUsername not implemented")
}
func (UnimplementedAuthServiceServer) ChangeUsername(context.Context, *ChangeUsernameRequest) (*ChangeUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeUsername not implemented")
}
func (UnimplementedAuthServiceServer) ChangeNickname(context.Context, *ChangeNicknameRequest) (*ChangeNicknameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeNickname not implemented")
}
func (UnimplementedAuthServiceServer) ChangeTelegramUsername(context.Context, *ChangeTelegramUsernameRequest) (*ChangeTelegramUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeTelegramUsername not implemented")
}
func (UnimplementedAuthServiceServer) ChangeAvatar(context.Context, *ChangeAvatarRequest) (*ChangeAvatarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeAvatar not implemented")
}
func (UnimplementedAuthServiceServer) GetUserIdentity(context.Context, *GetUserIdentityRequest) (*GetUserIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserIdentity not implemented")
}
func (UnimplementedAuthServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedAuthServiceServer) SuggestUsernameAlternatives(context.Context, *SuggestUsernameAlternativesRequest) (*SuggestUsernameAlternativesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestUsernameAlternatives not implemented")
}
func (UnimplementedAuthServiceServer) Enable2FA(context.Context, *Enable2FARequest) (*Enable2FAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable2FA not implemented")
}
func (UnimplementedAuthServiceServer) Verify2FA(context.Context, *Verify2FARequest) (*Verify2FAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify2FA not implemented")
}
func (UnimplementedAuthServiceServer) Disable2FA(context.Context, *Disable2FARequest) (*Disable2FAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disable2FA not implemented")
}
func (UnimplementedAuthServiceServer) GetAnomalyStats(context.Context, *GetAnomalyStatsRequest) (*GetAnomalyStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnomalyStats not implemented")
}
func (UnimplementedAuthServiceServer) GetAccountReadiness(context.Context, *GetAccountReadinessRequest) (*GetAccountReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountReadiness not implemented")
}
func (UnimplementedAuthServiceServer) GetTelegramIdentityHistory(context.Context, *GetTelegramIdentityHistoryRequest) (*GetTelegramIdentityHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelegramIdentityHistory not implemented")
}
func (UnimplementedAuthServiceServer) GetPublicProfile(context.Context, *GetPublicProfileRequest) (*PublicProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicProfile not implemented")
}
func (UnimplementedAuthServiceServer) FindUserByUsername(context.Context, *FindUserByUsernameRequest) (*FindUserByUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserByUsername not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_TelegramAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TelegramAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_TelegramAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TelegramAuth(ctx, req.(*TelegramAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_TelegramLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TelegramLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_TelegramLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TelegramLogin(ctx, req.(*TelegramLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LinkTelegramAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LinkTelegramAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LinkTelegramAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LinkTelegramAccount(ctx, req.(*LinkTelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EnableSeedPhrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableSeedPhraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EnableSeedPhrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_EnableSeedPhrase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EnableSeedPhrase(ctx, req.(*EnableSeedPhraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifySeedPhrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySeedPhraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifySeedPhrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifySeedPhrase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifySeedPhrase(ctx, req.(*VerifySeedPhraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DisableSeedPhrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableSeedPhraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DisableSeedPhrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DisableSeedPhrase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DisableSeedPhrase(ctx, req.(*DisableSeedPhraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetSeedPhraseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeedPhraseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetSeedPhraseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetSeedPhraseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetSeedPhraseStatus(ctx, req.(*GetSeedPhraseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeEmail(ctx, req.(*ChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeTelegramAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTelegramAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeTelegramAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeTelegramAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeTelegramAccount(ctx, req.(*ChangeTelegramAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_TerminateAllSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateAllSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TerminateAllSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_TerminateAllSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TerminateAllSessions(ctx, req.(*TerminateAllSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LinkEmailToAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LinkEmailToAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LinkEmailToAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LinkEmailToAccount(ctx, req.(*LinkEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SyncUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SyncUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SyncUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SyncUsername(ctx, req.(*SyncUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeUsername(ctx, req.(*ChangeUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeNickname(ctx, req.(*ChangeNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeTelegramUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTelegramUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeTelegramUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeTelegramUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeTelegramUsername(ctx, req.(*ChangeTelegramUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeAvatar(ctx, req.(*ChangeAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserIdentity(ctx, req.(*GetUserIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SuggestUsernameAlternatives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestUsernameAlternativesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SuggestUsernameAlternatives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SuggestUsernameAlternatives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SuggestUsernameAlternatives(ctx, req.(*SuggestUsernameAlternativesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Enable2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Enable2FARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Enable2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Enable2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Enable2FA(ctx, req.(*Enable2FARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Verify2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Verify2FARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Verify2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Verify2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Verify2FA(ctx, req.(*Verify2FARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Disable2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Disable2FARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Disable2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Disable2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Disable2FA(ctx, req.(*Disable2FARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAnomalyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnomalyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAnomalyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetAnomalyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAnomalyStats(ctx, req.(*GetAnomalyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAccountReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAccountReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetAccountReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAccountReadiness(ctx, req.(*GetAccountReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetTelegramIdentityHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelegramIdentityHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetTelegramIdentityHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetTelegramIdentityHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetTelegramIdentityHistory(ctx, req.(*GetTelegramIdentityHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetPublicProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetPublicProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetPublicProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetPublicProfile(ctx, req.(*GetPublicProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_FindUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindUserByUsername(ctx, req.(*FindUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "refreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "telegramAuth",
			Handler:    _AuthService_TelegramAuth_Handler,
		},
		{
			MethodName: "telegramLogin",
			Handler:    _AuthService_TelegramLogin_Handler,
		},
		{
			MethodName: "linkTelegramAccount",
			Handler:    _AuthService_LinkTelegramAccount_Handler,
		},
		{
			MethodName: "enableSeedPhrase",
			Handler:    _AuthService_EnableSeedPhrase_Handler,
		},
		{
			MethodName: "verifySeedPhrase",
			Handler:    _AuthService_VerifySeedPhrase_Handler,
		},
		{
			MethodName: "disableSeedPhrase",
			Handler:    _AuthService_DisableSeedPhrase_Handler,
		},
		{
			MethodName: "getSeedPhraseStatus",
			Handler:    _AuthService_GetSeedPhraseStatus_Handler,
		},
		{
			MethodName: "changePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
		{
			MethodName: "changeEmail",
			Handler:    _AuthService_ChangeEmail_Handler,
		},
		{
			MethodName: "changeTelegramAccount",
			Handler:    _AuthService_ChangeTelegramAccount_Handler,
		},
		{
			MethodName: "terminateAllSessions",
			Handler:    _AuthService_TerminateAllSessions_Handler,
		},
		{
			MethodName: "linkEmailToAccount",
			Handler:    _AuthService_LinkEmailToAccount_Handler,
		},
		{
			MethodName: "syncUsername",
			Handler:    _AuthService_SyncUsername_Handler,
		},
		{
			MethodName: "changeUsername",
			Handler:    _AuthService_ChangeUsername_Handler,
		},
		{
			MethodName: "changeNickname",
			Handler:    _AuthService_ChangeNickname_Handler,
		},
		{
			MethodName: "changeTelegramUsername",
			Handler:    _AuthService_ChangeTelegramUsername_Handler,
		},
		{
			MethodName: "changeAvatar",
			Handler:    _AuthService_ChangeAvatar_Handler,
		},
		{
			MethodName: "getUserIdentity",
			Handler:    _AuthService_GetUserIdentity_Handler,
		},
		{
			MethodName: "getUserProfile",
			Handler:    _AuthService_GetUserProfile_Handler,
		},
		{
			MethodName: "suggestUsernameAlternatives",
			Handler:    _AuthService_SuggestUsernameAlternatives_Handler,
		},
		{
			MethodName: "enable2FA",
			Handler:    _AuthService_Enable2FA_Handler,
		},
		{
			MethodName: "verify2FA",
			Handler:    _AuthService_Verify2FA_Handler,
		},
		{
			MethodName: "disable2FA",
			Handler:    _AuthService_Disable2FA_Handler,
		},
		{
			MethodName: "getAnomalyStats",
			Handler:    _AuthService_GetAnomalyStats_Handler,
		},
		{
			MethodName: "getAccountReadiness",
			Handler:    _AuthService_GetAccountReadiness_Handler,
		},
		{
			MethodName: "getTelegramIdentityHistory",
			Handler:    _AuthService_GetTelegramIdentityHistory_Handler,
		},
		{
			MethodName: "getPublicProfile",
			Handler:    _AuthService_GetPublicProfile_Handler,
		},
		{
			MethodName: "findUserByUsername",
			Handler:    _AuthService_FindUserByUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
